auth/auth signin
kalgory/Web_Kalgory-Admin pull request #5
Opened 2021-02-16 08:30 UTC by wildDoubt

## Feature
이메일 패스워드로 로그인할 수 있는 로그인 페이지를 만듦
## Changes 
- App.vue: router view 태그만 작동하도록 변경
- SignIn.vue: 로그인 페이지
- router/index.vue: about은 삭제하고 signin을 라우터에 등록
- SignInForm.vue: 로그인 폼 구현
- EmailTextField.vue: 이메일 텍스트 컴포넌트 구현
- PasswordTextField.vue: 패스워드 텍스트 컴포넌트 구현
- firebase/auth/index.js: 로그인 로그아웃 함수 추가
- main.js: firebase/index.js 추가

2021-02-16 08:34 UTC, wildDoubt commented
v-flex부분은 다시 고치는 중

2021-02-16 12:03 UTC, hyunmindev requested changes

2021-02-16 12:03 UTC, hyunmindev commented on src/views/sign-in/SignIn.vue
> +            :cols="6"
이부분 굳이 v-bind 로 받아야하나

2021-02-16 12:03 UTC, hyunmindev commented on src/views/sign-in/SignIn.vue
> +  </v-app>
v-app v-main은 app.vue에만 있으면 됨

2021-02-16 12:03 UTC, hyunmindev commented
그리고 views/sign-in/SignIn.vue는 메인프로젝트 구조 참고하고

2021-02-16 12:24 UTC, hyunmindev requested changes

2021-02-16 12:24 UTC, hyunmindev commented on src/components/sign-in/SignInForm.vue
> +      @keydown.enter="submit"
이부분 수정

2021-02-16 12:24 UTC, hyunmindev commented on src/components/sign-in/SignInForm.vue
> +  components: { PasswordTextField, EmailTextField },
줄바꿈으로 표시

2021-02-16 12:26 UTC, hyunmindev requested changes

2021-02-16 12:26 UTC, hyunmindev commented on src/App.vue
>    </v-app>
<v-main>

2021-02-17 06:18 UTC, hyunmindev commented
굳 전체적으로 훨씬 깔끔해졌다

2021-02-17 06:19 UTC, hyunmindev requested changes

2021-02-17 06:19 UTC, hyunmindev commented on src/router/index.js
> +    name: 'SignIn',
route 네임은 그냥 소문자로 sign in
메인 프로젝트 참고

2021-02-17 06:20 UTC, hyunmindev commented
email textfield password textfield
validate on blur props 설정해논거 메인프로젝트 참고후에 수정해보시길

2021-02-17 06:26 UTC, wildDoubt commented
route name 수정하고, lazy loading 적용시켜볼게. 어제 하다가 계속 안되서 오늘 다시 해봐야할듯..
validate on blur props 이거는 라우트 해결되면 바로 할게

2021-02-17 08:27 UTC, wildDoubt commented
validate-on-blur 저거는 이해했는데 라우트 lazy loading 적용하면 에러남.

2021-02-17 08:28 UTC, hyunmindev commented
may i help you?

2021-02-17 11:55 UTC, wildDoubt commented
라우터 문제 해결함.
vue-router 패키지는 메인 프로젝트랑 버전 통일시켰음.

2021-02-18 09:06 UTC, hyunmindev approved these changes
Good

2021-02-18 09:07 UTC, wildDoubt commented
Thx

2021-02-18 09:07 UTC, merged