feature/dashboard
kalgory/Web_Kalgory-Admin pull request #7
Opened 2021-02-27 07:12 UTC by wildDoubt

## Feature
대시보드 추가 및 라우터 가드 변경
## Changes

- routes.js: 라우터 구조 추가
- App.vue: progress bar, footer 추가
- permission.js: router.beforeEach로 네비게이션 가드 설정
- plugins/token: 제거
- BaseDashboard.vue: 대시보드 추가
- store/modules/auth: user를 저장하는 상태 추가
- AppBar.vue: 타이틀과 로그아웃 버튼이 있는 앱 바 추가
- AppSideBar.vue: 앱 바에서 toggle버튼으로 열고 닫을 수 있는 sidebar를 왼쪽에 추가. 스크린 사이즈가 mobile breakpoint를 넘어도 제대로 작동하도록 만듦
- BarMenu: 가독성을 위해 AppSideBar에서 출력하는 메뉴 컴포넌트를 따로 만듦
- plugins/firebase/firestore/user: admin유저인지 판단하는 함수 추가(user document의 is_admin 필드 참조)
- BaseCommunity.vue: Community 관리 컴포넌트(현재 기능 없음)
- BaseConcept.vue: Concept 관리 컴포넌트(현재 기능 없음)
- BaseProblem.vue: Problem 관리 컴포넌트(현재 기능 없음)
- BaseUser.vue: User 관리 컴포넌트(현재 기능 없음)
- assests/: 칼고리 이미지 추가
- AppFooter.vue: footer 컴포넌트

## Summary
![대시보드 이미지](https://user-images.githubusercontent.com/64261939/109378444-f2d12900-7915-11eb-8bd5-db678788f373.png)

- **네비게이션 가드 변경**

  메인 프로젝트에 적용된 네비게이션 가드랑 admin 로그인판단하는 함수랑 같이 사용하기 어려워서 onAuthStateChanged를 unsubscribe하는 방식으로 라우터 가드를 다시 설정함.

- **대시보드 구성**

  Community, Concept, Problem, User 탭으로 이동할 수 있도록 app bar를 추가함. 로그아웃 버튼을 우측 상단에 위치함.

2021-02-27 09:40 UTC, wildDoubt commented
admin 판단하는 부분 promise 중첩으로 정리하긴 했는데 맞게 한건지 잘 모르겠음

2021-02-28 11:15 UTC, hyunmindev requested changes

2021-02-28 11:15 UTC, hyunmindev commented on src/assets/Logo-Initial-Background-lazy.svg
> +</svg>
사용하지 않는 파일 삭제

2021-02-28 11:15 UTC, hyunmindev commented on src/components/app/AppBar.vue
> +};
signOut 메소드 내에 Auth Loading 처리해주는 부분 필요할듯

2021-02-28 11:15 UTC, hyunmindev commented on src/components/app/bar/BarMenu.vue
> +<template>
컴포넌트 이름이 컨벤션과 일치하지 않음
app/navigation-drawer/NavigationDrawerList.vue
이건 어때

2021-02-28 11:15 UTC, hyunmindev commented on src/components/app/bar/BarMenu.vue
> +          path: 'community',
path 에 root(/)가 없음

2021-02-28 11:15 UTC, hyunmindev commented on src/components/app/bar/BarMenu.vue
> +          path: 'problem',
path 에 root(/)가 없음

2021-02-28 11:15 UTC, hyunmindev commented on src/components/auth/sign-in/SignInForm.vue
> +import { isAdminUser } from '@/plugins/firebase/firestore/user';
함수이름이 boolean 변수명같음

2021-02-28 11:15 UTC, hyunmindev commented on src/components/auth/sign-in/SignInForm.vue
> +            }
변수명만 다시 설정하면 될듯 문제없어보인다
여기서 throw 해도 밑에 catch로 넘어감?

2021-02-28 11:15 UTC, hyunmindev commented on src/plugins/firebase/auth/index.js
> +// import { isAdminUser } from '../firestore/user';
주석 삭제

2021-02-28 11:15 UTC, hyunmindev commented on src/plugins/firebase/firestore/user/index.js
> +export function isAdminUser(userUID) {
함수 명 정정바람

2021-02-28 11:15 UTC, hyunmindev commented on src/plugins/firebase/firestore/user/index.js
> +        querySnapshot.forEach((QueryDocumentSnapshot) => {
이 부분은 사이즈가 무조건 1일때 실행될 부분인데 forEach를쓰는건 부자연스러움
그리고 쿼리스냅샷의 사이즈가 0일시에 catch로 넘어가는거 실험부탁함

2021-02-28 11:15 UTC, hyunmindev commented on src/router/index.js
> +  store.commit('setIsAuthLoading', false);
오잉?

2021-02-28 11:16 UTC, hyunmindev commented
getCurrentUser  부분은 일단 삭제하고 네비게이션 가드 다시 만들때 다시 고려해보자

2021-02-28 11:29 UTC, hyunmindev commented on src/components/auth/sign-in/SignInForm.vue
> +            }
다시 생각해보니 여기서 isAdmin 이 false인 상황에 캣치로 넘기는게 흐름적으로 어색하다
그냥 사인아웃해주고 에러토스트 띄우는걸로 충분할듯

2021-02-28 11:36 UTC, wildDoubt commented on src/plugins/firebase/firestore/user/index.js
> +export function isAdminUser(userUID) {
checkAdmin어때?

2021-02-28 12:15 UTC, wildDoubt commented on src/components/auth/sign-in/SignInForm.vue
> +            }
테스트해보니까 밑에 catch로 바로 넘어감.
난 에러 던져서 로그인을 아예 안되게 하려고 저렇게 만들었는데 바로 signOut시켜도 되겠네

2021-02-28 12:44 UTC, wildDoubt commented on src/plugins/firebase/firestore/user/index.js
> +        querySnapshot.forEach((QueryDocumentSnapshot) => {
쿼리스냅샷 사이즈 0일 떄 밑에 있는 catch로 안 넘어가서 
```javascript
        if (querySnapshot.size > 1) {
          reject(Error('Duplicate users with same userUID'));
        }
        if (querySnapshot.empty) {
          reject(Error('No data!'));
        }
        resolve(querySnapshot.docs[0].data().is_admin);
```
이런 식으로 바꿨는데 ㄱㅊ? 맨 밑에 줄은 forEach 수정한 코드

2021-03-01 05:25 UTC, hyunmindev approved these changes
커렌트 유저 네비게이션 가드 관련해서 브랜치 하나 팝시다

2021-03-01 05:26 UTC, merged